In [3]:
import torch

In [4]:
print(torch.__version__)

2.6.0+cu124


### Check is connected to GPU or not :

In [5]:
if torch.cuda.is_available():
    print("Connected to GPU")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("Not connected to GPU")

Connected to GPU
Using GPU : Tesla T4


### Create Tensor in Pytorch

In [30]:
a = torch.empty(2,4)   # it generates a random valued tensor of given size
a

tensor([[6.8611e-34, 6.0993e-38, 6.2815e-38, 0.0000e+00],
        [0.0000e+00, 5.9135e-43, 5.9835e-43, 0.0000e+00]])

In [9]:
type(a)

torch.Tensor

In [10]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
torch.rand(2,4) # gives a random valued (0 to 1) tensor of the given size  , it is use in the cases like weight initialization and all

tensor([[0.0636, 0.7071, 0.8613, 0.9795],
        [0.4406, 0.0162, 0.7157, 0.4664]])

In [14]:
torch.rand(2,4)  # every time it will give different values , to get same values we have to use seed

tensor([[0.8245, 0.0124, 0.5725, 0.8354],
        [0.8783, 0.4712, 0.4434, 0.4071]])

manual seed

In [15]:
torch.manual_seed(100)  # now it will give same values every time with this seed
torch.rand(2,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [16]:
torch.manual_seed(100)
torch.rand(2,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

Create Manual Tensor(Custom Tensor)

In [22]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In a range

In [23]:
print("using arange -> : " , torch.arange(0,10,2))

using arange -> :  tensor([0, 2, 4, 6, 8])


In [24]:
# linspace : Linerly spaced
print("using linspace -> : " , torch.linspace(0,10,10))

using linspace -> :  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [25]:
# indenty matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
# all element of a given value
torch.full((3,3),6)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

# Shapes in Tensor

In [28]:
x = torch.tensor([[2,1,3],[4,5,6]])
x

tensor([[2, 1, 3],
        [4, 5, 6]])

In [29]:
x.shape

torch.Size([2, 3])

In [31]:
# create a tensor y which has same shape of x
torch.empty_like(x)

tensor([[90194313439,           1,   261892120],
        [  261892064,          24,     9924480]])

In [32]:
# another way to get the same shape
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [40]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2080, 0.1180, 0.1217],
        [0.7356, 0.7118, 0.7876]])

In [33]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Data Type in Tensor

In [34]:
x.dtype

torch.int64

In [37]:
# define the data type while creating the tensor
torch.tensor([[1.0,2.0,3.0]] , dtype = torch.int64)

tensor([[1, 2, 3]])

In [38]:
# change the data type of an existing tensor
x.to(torch.float64)

tensor([[2., 1., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# mathematical Operation

In [42]:
# 1. Scaler Operation :  addition , subtraction , multiplicatin , division, int   divion , mod , power
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [43]:
x +2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [44]:
x-2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [45]:
x/2

tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])

In [46]:
x//2

tensor([[0., 0.],
        [0., 0.]])

In [47]:
x*2

tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])

In [48]:
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

In [49]:
x%2

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

# Element vise operation on two tensors

In [54]:
a = torch.rand(2,2)
a

tensor([[0.5277, 0.2472],
        [0.7909, 0.4235]])

In [55]:
b = torch.rand(2,2)
b

tensor([[0.0169, 0.2209],
        [0.9535, 0.7064]])

In [57]:
 a+b

tensor([[0.5446, 0.4681],
        [1.7444, 1.1299]])

In [58]:
a-b

tensor([[ 0.5108,  0.0263],
        [-0.1627, -0.2829]])

In [59]:
a*b

tensor([[0.0089, 0.0546],
        [0.7541, 0.2992]])

In [60]:
# make abs
c = torch.tensor([[1,-2,3],[4,-5,6]])
torch.abs(c)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [61]:
# negative
torch.neg(c)

tensor([[-1,  2, -3],
        [-4,  5, -6]])

In [62]:
# round
torch.round(torch.tensor([1.2,1.5,1.8]))

tensor([1., 2., 2.])

In [69]:
# Similarly : Floor , Ceil

# Clamp : make all the number within a range
torch.clamp(torch.tensor([[1.6, 4.5 , 1.4, 2.4]]) , min = 1 , max = 2)

tensor([[1.6000, 2.0000, 1.4000, 2.0000]])

In [76]:
e = torch.randint(size = (2,3) , low = 0 , high = 10, dtype = torch.float32)
e

tensor([[7., 9., 2.],
        [6., 7., 7.]])

In [72]:
# Sum of all element
torch.sum(e)


tensor(47)

In [73]:

# Col sum
# Row Sum
torch.sum(e, dim =0)

tensor([18, 15, 14])

In [74]:
# Similary Mean , Median ,  min , max , product

In [77]:
# Standard Deviation
torch.std(e)

tensor(2.3381)

In [78]:
torch.var(e)

tensor(5.4667)

In [79]:
# get the postion of max value
torch.argmax(e)  # start with 0

tensor(1)

In [81]:
# matrix multiplication
f = torch.randint(size = (2,3) , low = 0 , high = 10)
g = torch.randint(size = (3,2) , low = 0 , high = 10)

In [83]:
torch.matmul(f,g)

tensor([[12, 24],
        [36, 88]])

In [85]:
vec1 = torch.tensor([2,3])
vec2 = torch.tensor([5,6])

torch.dot(vec1,vec2)

tensor(28)

In [86]:
# transpose
torch.transpose(e,0,1)

tensor([[7., 6.],
        [9., 7.],
        [2., 7.]])

In [90]:
torch.det(torch.rand(3,3))

tensor(0.0560)

In [91]:
torch.inverse(torch.rand(3,3))

tensor([[ 1.1985, -0.1945, -0.0576],
        [-0.0703, -2.3994,  3.6842],
        [-0.3784,  1.6468, -0.7403]])

# Copy in a Tensor


In [94]:
# use clone to permanently copying
a = torch.rand(2,2)
a

tensor([[0.9157, 0.3079],
        [0.6269, 0.8277]])

In [95]:
b = a
b

tensor([[0.9157, 0.3079],
        [0.6269, 0.8277]])

In [96]:
a[0][0] = 0

In [98]:
b   # here we can see b also changes if we change the a

tensor([[0.0000, 0.3079],
        [0.6269, 0.8277]])

In [100]:
b = a.clone()
b

tensor([[0.0000, 0.3079],
        [0.6269, 0.8277]])

In [101]:
 a[0][1] = 1

In [102]:
a

tensor([[0.0000, 1.0000],
        [0.6269, 0.8277]])

In [103]:
b  # now b does not change with a

tensor([[0.0000, 0.3079],
        [0.6269, 0.8277]])

# Tensors Operations on GPUs

In [104]:
# check If I am using GPU or not
torch.cuda.is_available()

True

In [105]:
device = torch.device('cuda')

In [106]:
# Create New Tensor on GPU
a = torch.rand(2,2, device = device)


In [107]:
# Change the existinng CPU into GPU
b  = torch.rand(2,2)
b = b.to(device)

# Change the shape of a Tensor

In [ ]:
# a.reshape()

#  Flatten
# a.flatten()
# permute
# unsqueeze

# Numpy and Torch

In [108]:
import numpy as np

In [109]:
a = torch.tensor([1,2,3])

In [112]:
b =a.numpy() # convert into numpy tesnor
b

array([1, 2, 3])

In [113]:
type(b)

numpy.ndarray

In [114]:
c = np.array([1,2,3])

In [115]:
c

array([1, 2, 3])

In [116]:
torch.from_numpy(c)  # numpy to torch

tensor([1, 2, 3])