In [42]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [43]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [44]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [45]:
df.shape

(569, 33)

In [46]:
df.drop(columns = ['id' , 'Unnamed: 32'] , inplace = True)

Split

In [47]:
X_train , X_test , y_train , y_text =train_test_split(df.iloc[:,1:] , df.iloc[:,0] , test_size = 0.2)

Scaling

In [48]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [49]:
X_train

array([[-0.30301658, -0.81823141, -0.26652122, ..., -0.65521959,
         0.41750673, -0.10314112],
       [-0.32555826,  1.38167302, -0.39035735, ..., -0.86978271,
        -0.97069585, -1.15330214],
       [-0.35655307, -0.82056676, -0.3300795 , ..., -0.2004151 ,
        -1.45609242, -0.6892775 ],
       ...,
       [-0.0381518 , -0.82990818, -0.10414005, ..., -0.50823913,
        -1.23948223, -0.92073477],
       [-0.55661051,  0.30507436, -0.61137616, ..., -0.63190436,
        -0.35723047, -0.8274858 ],
       [-0.24948008, -1.04009014, -0.30301597, ..., -0.22562075,
        -1.41182173, -1.20048168]])

In [50]:
y_train

20     B
458    B
284    B
518    B
482    B
      ..
13     M
290    B
439    B
102    B
92     B
Name: diagnosis, Length: 455, dtype: object

In [51]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_text = encoder.transform(y_text)


In [52]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,

Numpy array to torch

In [71]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_text)


In [54]:
X_train_tensor.shape

torch.Size([455, 30])

In [55]:
y_train_tensor.shape

torch.Size([455])

Define Model

In [62]:
class nn:
    def __init__(self , X):
        self.w = torch.rand(X.shape[1],1 , dtype = torch.float64 , requires_grad = True)
        self.b = torch.zeros(1 , dtype = torch.float64 , requires_grad = True)

    def forward(self , X):
        z = torch.matmul(X , self.w) + self.b
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

Imp Parameters

In [63]:
learing_rate = 0.1
epochs = 25

Training Pipeline

In [68]:
# Create Model
model = nn(X_train_tensor)

# Define loop : number of epochs

for epoch in range (epochs):
  # Forward
  y_pred = model.forward(X_train_tensor)
  # Loss
  loss = model.loss_function(y_pred , y_train_tensor)
  # Backward
  loss.backward()
  # Update
  with torch.no_grad():  # to avoid Gradient Tracking (Calculation of gradient after training)
    model.w -= learing_rate * model.w.grad
    model.b -= learing_rate * model.b.grad

  # zero gradients to # Clearing Grad : initialize with 0 every time before moving to next epoch otherwise gradient will accumulate
  model.w.grad.zero_()
  model.b.grad.zero_()

  print(f'Epoch {epoch+1} , Loss : {loss.item()}')

Epoch 1 , Loss : 3.5183009043648275
Epoch 2 , Loss : 3.385830974091468
Epoch 3 , Loss : 3.245761359227618
Epoch 4 , Loss : 3.100821797862005
Epoch 5 , Loss : 2.9522090850187097
Epoch 6 , Loss : 2.8021441489251857
Epoch 7 , Loss : 2.642320526453015
Epoch 8 , Loss : 2.4759301090019807
Epoch 9 , Loss : 2.303630475459012
Epoch 10 , Loss : 2.1295789266719356
Epoch 11 , Loss : 1.9602716564081661
Epoch 12 , Loss : 1.7938346229180293
Epoch 13 , Loss : 1.6345334342854843
Epoch 14 , Loss : 1.4813522401919121
Epoch 15 , Loss : 1.337426457721901
Epoch 16 , Loss : 1.2057166224632991
Epoch 17 , Loss : 1.092264133201989
Epoch 18 , Loss : 0.9984552235602823
Epoch 19 , Loss : 0.9243813614186179
Epoch 20 , Loss : 0.8686169189110131
Epoch 21 , Loss : 0.8284136575072416
Epoch 22 , Loss : 0.8003061979306648
Epoch 23 , Loss : 0.7808765861628052
Epoch 24 , Loss : 0.7673006862120502
Epoch 25 , Loss : 0.7575205885260388


In [69]:
model.b

tensor([-0.1362], dtype=torch.float64, requires_grad=True)

In [74]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.640350878238678
